Repository Bridgeconn/vachan-api, pull requests merged in 2023-09, with the labels that each got.

#699 Error fixing on landing page
  app/routers/auth_api.py
  app/routers/content_apis.py
  app/routers/filehandling_apis.py
  app/routers/media_api.py
  app/routers/translation_apis.py
  app/templates/landing_page.html
  requirements.txt
Labels: bug

#701 changes in reference validation
  app/crud/contents_crud.py
  app/schema/schema_content.py
Labels: enhancement

#707 LANDING PAGE: UI Fix
  app/static/css/hugo-styles.css
  app/static/css/styles.css
  app/static/images/graphql.png
  app/static/scripts/scripts.js
  app/templates/landing_page.html
Labels: bug, enhancement
