Repository Bridgeconn/vachan-api, pull requests merged in 2023-08, with the labels that each got.

#659 content -> resource types ;changes in terminologies
  app/auth/api-permissions.csv
  app/auth/authentication.py
  app/crud/contents_crud.py
  app/crud/nlp_sw_crud.py
  app/crud/structurals_crud.py
  app/db_models.py
  app/routers/content_apis.py
  app/routers/media_api.py
  app/routers/translation_apis.py
  app/schema/schema_auth.py
  app/schema/schema_content.py
  app/schema/schemas.py
  app/test/__init__.py
  app/test/test_agmt_projects.py
  app/test/test_bible_audios.py
  app/test/test_bibles.py
  app/test/test_commentaries.py
  app/test/test_languages.py
  app/test/test_licenses.py
  app/test/test_media.py
  app/test/test_parascripturals.py
  app/test/test_resource_types.py
  app/test/test_resources.py
  app/test/test_sign_bible_videos.py
  app/test/test_smast_projects.py
  app/test/test_source_get_sentence.py
  app/test/test_stop_words_generation.py
  app/test/test_translation_workflow.py
  app/test/test_versions.py
  app/test/test_vocabularies.py
  db/seed_DB.sql
Labels: enhancement

#661 UPDATE: updated new endpoints for Data Manipulation
  app/auth/api-permissions.csv
  app/auth/authentication.py
  app/routers/content_apis.py
  app/test/test_agmt_projects.py
  app/test/test_agmt_translation2.py
  app/test/test_bible_audios.py
  app/test/test_bibles.py
  app/test/test_commentaries.py
  app/test/test_deleted_items.py
  app/test/test_languages.py
  app/test/test_licenses.py
  app/test/test_parascripturals.py
  app/test/test_resource_types.py
  app/test/test_resources.py
  app/test/test_sign_bible_videos.py
  app/test/test_smast_projects.py
  app/test/test_smast_translation2.py
  app/test/test_stop_words_generation.py
  app/test/test_translation_suggestions.py
  app/test/test_versions.py
  app/test/test_vocabularies.py
Labels: enhancement

#662 Bugfix/response validation error in suggestions
  app/crud/nlp_tokenization.py
Labels: bug, translation module

#689 translation projects shows same createTime
  app/crud/projects_crud.py
  app/test/test_agmt_projects.py
  app/test/test_smast_projects.py
Labels: bug
