Repository Bridgeconn/vachan-api, pull requests merged in 2023-06, with the labels that each got.

#581 Use profiles in docker compose
  .github/workflows/deploy.yml
  .github/workflows/deploy_prod.yaml
  .github/workflows/run-test.yml
  README.md
  docker/docker-compose.yml
  docker/production-deploy.yml
  docker/run-test-dependencies.yml
  docker/run-tests.yml
  docs/Vachan-deployment-steps.md
  docs/docker-guide.md
Labels: deployment

#590 Adding localScriptName field in language APIs and GET source
  app/crud/structurals_crud.py
  app/db_models.py
  app/graphql_api/queries.py
  app/routers/content_apis.py
  app/schema/schemas.py
  app/test/test_languages.py
  app/test/test_sources.py
  db/seed_DB.sql
Labels: enhancement

#593 Bugfix/gloss not updated from project
  .github/workflows/check-linting.yml
  app/.pylintrc
  app/crud/projects_crud.py
  app/test/test_agmt_translation2.py
  docker/Kratos_config/quickstart.yml
Labels: translation module

#597 update on documentation
  README.md
Labels: documentation

#594 Add x-experimental to a few endpoints
  app/main.py
Labels: documentation

#603 Bugfix/draft missing confirmed word after suggestions
  app/crud/nlp_tokenization.py
  app/crud/projects_crud.py
  app/crud/utils.py
  app/routers/translation_apis.py
  app/test/test_agmt_translation2.py
  app/test/test_smast_translation2.py
Labels: translation module

#604 Use CICD bot's account to push upon bump version
  .github/workflows/deploy_release.yml
Labels: deployment
