Repository Bridgeconn/vachan-api, pull requests merged in 2023-07, with the labels that each got.

#611 Include createdUser in GET source response
  app/schema/schemas.py
  app/test/test_sources.py
Labels: enhancement

#630 Handle spaces or other in-between segments when doing token replacement
  app/crud/nlp_tokenization.py
  app/test/test_generic_translation.py
Labels: bug, translation module

#633 Use container name "kratos" instead of domain in Docker compose
  docker/docker-compose.yml
Labels: bug, deployment

#637 Fix cicd bot's push rights to version-2: trail #1
  .github/workflows/deploy_release.yml
Labels: bug, deployment

#638 Fix cicd bot's push rights to version-2: trail #2
  .github/workflows/deploy_release.yml
Labels: deployment

#643 New App:VachanContentDashboard with admin and user
  app/auth/access_rules.json
  app/auth/api-permissions.csv
  app/auth/authentication.py
  app/routers/auth_api.py
  app/schema/schema_auth.py
  app/test/__init__.py
  app/test/conftest.py
  app/test/test_agmt_projects.py
  app/test/test_agmt_translation.py
  app/test/test_agmt_translation2.py
  app/test/test_bible_videos.py
  app/test/test_bibles.py
  app/test/test_commentaries.py
  app/test/test_content_types.py
  app/test/test_dictionaries.py
  app/test/test_infographics.py
  app/test/test_languages.py
  app/test/test_licenses.py
  app/test/test_nlp_glossary.py
  app/test/test_smast_projects.py
  app/test/test_smast_translation.py
  app/test/test_smast_translation2.py
  app/test/test_sources.py
  app/test/test_stop_words_generation.py
  app/test/test_translation_suggestions.py
  app/test/test_versions.py
Labels: enhancement

#649 languages -> resources/languages
  app/auth/api-permissions.csv
  app/auth/authentication.py
  app/routers/content_apis.py
  app/test/test_deleted_items.py
  app/test/test_languages.py
Labels: enhancement
