Repository Bridgeconn/vachan-api, pull requests merged in 2023-04, with the labels that each got.

#537 PUT API for Glossary
  app/auth/api-permissions.csv
  app/crud/nlp_crud.py
  app/db_models.py
  app/routers/translation_apis.py
  app/schema/schemas_nlp.py
  app/test/test_nlp_glossary.py
  app/test/test_translation_suggestions.py
Labels: enhancement, translation module

#539 Bugfix/erv bible upload
  app/auth/authentication.py
  app/crud/contents_crud.py
  app/custom_exceptions.py
  app/test/test_bibles.py
Labels: bug, high priority

#541 Change version tag in API docs to beta.5
  app/main.py
Labels: documentation

#547 Feature/vachan demos service
  app/main.py
  docker/docker-compose.yml
  docker/nginx/default.conf
  docker/nginx/prod/app.conf.template
  docker/production-deploy.yml
Labels: enhancement, deployment

#553 Try to add auto deployment to production, upon release
  .github/workflows/deploy_prod.yaml
Labels: enhancement, deployment

#554 Move auth db to main docker compose
  docker/production-deploy.yml
  docs/docker-guide.md
Labels: deployment
