Repository Bridgeconn/vachan-api, pull requests merged in 2023-05, with the labels that each got.

#570 Docker compose upgrade
  .github/workflows/deploy.yml
  .github/workflows/deploy_prod.yaml
  docker/Dockerfile
Labels: deployment

#577 Fix memory leak by applying join conditions inside rebuid_trie
  app/crud/nlp_crud.py
Labels: bug, translation module

#580 Adding "editable" permission to DELETE APIs of Contents
  app/auth/access_rules.json
  app/crud/contents_crud.py
  app/crud/media_crud.py
  app/routers/content_apis.py
  app/schema/schema_content.py
  app/schema/schemas_nlp.py
  app/test/test_bible_videos.py
  app/test/test_bibles.py
  app/test/test_commentaries.py
  app/test/test_dictionaries.py
  app/test/test_infographics.py
Labels: bug, enhancement
